[build]
  base = "."
  publish = "frontend/build"
  command = "cd frontend && CI=false npm install && npm run build"

[functions]
  directory = "backend/functions"
  external_node_modules = ["sqlite3"] 

[dev]
  framework = "#static"
  command = "cd frontend && npm start"
  targetPort = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
