[build]
  base = "frontend"
  publish = "build"
  command = "CI=false npm i && npm run build"

[functions]
  directory = "../backend/functions"
  external_node_modules = ["sqlite3"] 

[dev]
  framework = "#static"
  command = "npm start"
  targetPort = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
